### ISSUE TITLE
bash: cloud-import: command not found

### ISSUE THREAD

**Issue by talltechy** [ggMartinez/Proxmox-Cloud-Image-Importer#1]
pve 8.2.3
running Debian GNU/Linux 12 (bookworm)

`root@pve:/home/cockpitadm# cd /opt/Proxmox-Cloud-Image-Importer
root@pve:/opt/Proxmox-Cloud-Image-Importer# ls -la
total 40
drwxr-xr-x 3 root root    7 Sep  2 10:55 .
drwxr-xr-x 5 root root    5 Sep  2 10:55 ..
-rw-r--r-- 1 root root 2793 Sep  2 10:55 cloud-import.py
drwxr-xr-x 8 root root   13 Sep  2 10:55 .git
-rw-r--r-- 1 root root 1253 Sep  2 10:55 install.sh
-rw-r--r-- 1 root root 1395 Sep  2 10:55 README.md
-rw-r--r-- 1 root root   17 Sep  2 10:55 requirements.txt
root@pve:/opt/Proxmox-Cloud-Image-Importer# git pull
Already up to date.
root@pve:/opt/Proxmox-Cloud-Image-Importer# cloud-import
bash: cloud-import: command not found`

**Comment by ggMartinez** [comment]
Hi @talltechy, did you run the install script?

**Comment by ggMartinez** [comment]
The install script had a typo on the path where the link should be created. [Fixed with this commit. ](https://github.com/ggMartinez/Proxmox-Cloud-Image-Importer/commit/9675a887899e476a3bb81c84a64724f1a44595de)

Feel free to try again, sorry for the incovenience.
